abbr -a --global u 'update'
abbr -a --global ff 'fastfetch'
abbr -a --global lg 'lazygit'
abbr -a --global mm 'mintmedia'
abbr -a --global m 'micro'
abbr -a --global gs 'git status'
abbr -a --global l 'eza --git --group-directories-first'
abbr -a --global src 'source $__fish_config_dir/config.fish'
abbr -a --global ts 'tailscale'
