abbr -a --global a 'after'
abbr -a --global a_num --regex '^a([1-9][0-9]*)$' --function __abbr_timer_minutes
abbr -a --global u 'update'
abbr -a --global ff 'fastfetch'
abbr -a --global lg 'lazygit'
abbr -a --global v 'vim'
abbr -a --global m 'micro'
abbr -a --global fm 'fv -y'
abbr -a --global gs 'git status'
abbr -a --global src 'source $__fish_config_dir/config.fish'
abbr -a --global l 'eza -a --icons --git --group-directories-first'
abbr -a --global ts 'tailscale'
abbr -a --global mm 'mintmedia'
abbr -a --global caf 'caffeinate'
abbr -a --global portal 'curl -v http://neverssl.com 2>&1 | grep -i location'
alias please='sudo'
alias ..='cd ..'
alias ....='cd ../..'
alias ......='cd ../../..'
