exec swayidle -w \
    lock            'swaylock -f' \
    before-sleep    'swaylock -f' \
    timeout 300     'loginctl lock-session' \
    timeout 330     'swaymsg "output * power off"' \
         resume     'swaymsg "output * power on"'
