abbr -a a_num --regex '^a([1-9][0-9]*)$' --function __abbr_timer_minutes
abbr -a u 'update'
abbr -a a 'after'
abbr -a vn 'vpn on'
abbr -a vf 'vpn off'
abbr -a vs 'vpn status'
abbr -a mn 'media on'
abbr -a mf 'media off'
abbr -a ms 'media status'
abbr -a ff 'fastfetch'
abbr -a speed 'networkQuality'
abbr -a lg 'lazygit'
abbr -a mm 'mintmedia'
abbr -a m 'micro'
abbr -a gs 'git status'
abbr -a z 'cd'
