abbr -a --global a_num --regex '^a([1-9][0-9]*)$' --function __abbr_timer_minutes
abbr -a --global u 'brew update && brew upgrade --yes && brew cleanup'
abbr -a --global a 'after'
abbr -a --global ff 'fastfetch'
abbr -a --global speed 'networkQuality'
abbr -a --global lg 'lazygit'
abbr -a --global mm 'mintmedia'
abbr -a --global v 'vim'
abbr -a --global m 'vim -y'
abbr -a --global gs 'git status'
abbr -a --global gpr 'git pull --rebase'
abbr -a --global batt 'system_profiler SPPowerDataType | rg -i "cycle count|maximum capacity|condition"'
abbr -a --global gt 'after -q 3m; and say "your tea is ready now"'
abbr -a --global bt 'after -q 3m45s; and say "your tea is ready now"'
abbr -a --global l 'eza -a --icons --git --group-directories-first'
abbr -a --global src 'source $__fish_config_dir/config.fish'
abbr -a --global dr 'doctor'
abbr -a --global ts 'tailscale status'
abbr -a --global tu 'tailscale up'
abbr -a --global td 'tailscale down'
alias please='sudo'
alias ..='cd ..'
alias ....='cd ../..'
alias ......='cd ../../..'
