# ~/.config/fish/aliases.fish

# Using alias instead of abbr for internal function compatibility
alias u='update'
alias t='timer'
alias t3='timer 3m'
alias t4='timer 4m'
alias t5='timer 5m'
alias t10='timer 10m'
alias t20='timer 20m'
alias t30='timer 30m'
alias mm='mintmedia'
alias m='micro'
alias mn='media-on'
alias mf='media-off'
alias nu='nord-up'
alias nd='nord-down'
alias l='eza'
alias c='bat'
alias ff='fastfetch'
alias yto='yt -o'
alias yti='yt -i'
alias tm-on='brew services start transmission-cli'
alias tm-off='brew services stop transmission-cli'
alias tm-re='brew services restart transmission-cli'
alias tm-ping='transmission-remote 127.0.0.1:9091 -st'
alias speed='networkQuality'
alias lg='lazygit'
