# ~/.config/fish/aliases.fish

abbr -a u 'update'
abbr -a t 'timer'
abbr -a vn 'vpn on'
abbr -a vf 'vpn off'
abbr -a mn 'media on'
abbr -a mf 'media off'
abbr -a ff 'fastfetch'
abbr -a speed 'networkQuality'
abbr -a lg 'lazygit'
abbr -a mm 'mintmedia'
abbr -a m 'micro'
abbr -a gs 'git status'
abbr -a z 'cd'
abbr -a zl 'cdl'
abbr -a batt 'system_profiler SPPowerDataType'

alias gt='timer 3m -q; and say "your tea is ready now"'
alias bt='timer 4m -q; and say "your tea is ready now"'
alias l='eza --git --group-directories-first'
alias c='bat'
alias lab='media on; and ssh lab'
