# ~/.config/fish/aliases.fish

abbr -a u 'update'
abbr -a t 'timer'
abbr -a vn 'vpn-on'
abbr -a vf 'vpn-off'
abbr -a ff 'fastfetch'
abbr -a speed 'networkQuality'
abbr -a lg 'lazygit'
abbr -a mm 'mintmedia'
abbr -a m 'micro'
abbr -a mn 'media-on'
abbr -a mf 'media-off'

alias gt='timer 3m -q; and say "your tea is ready now"'
alias bt='timer 4m -q; and say "your tea is ready now"'
alias l='eza --git --group-directories-first'
alias c='bat'
alias tm-on='brew services start transmission-cli'
alias tm-off='brew services stop transmission-cli'
alias tm-re='brew services restart transmission-cli'
alias tm-ping='transmission-remote 127.0.0.1:9091 -st'
alias lab='media-on; and ssh lab'
alias gs='git status'
