# This file is generated by nixos-generate-config during installation.
# During install, after partitioning and mounting at /mnt, run:
#
#   nixos-generate-config --root /mnt
#
# then copy /mnt/etc/nixos/hardware-configuration.nix here, replacing this file.
# The stubs below match the T14 Gen 1 Intel baseline; filesystem UUIDs must be
# replaced with values from the generated file.

{ config, lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [];

  # Replace with actual UUIDs from nixos-generate-config output.
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
